added modes
ulitcos/react-canvas-confetti pull request #2
Opened 2021-03-09 17:39 UTC by DTau9

Hello! I added original confetti modes for your react-canvas-confetti library.

2021-03-14 12:21 UTC, DTau9 commented
@ulitcos  ?

2021-03-14 12:24 UTC, ulitcos commented on package.json
> +    "@storybook/react": "^6.1.21",
I'm planing save dependencies in static

2021-03-14 13:17 UTC, ulitcos requested changes

2021-03-20 22:07 UTC, ulitcos requested changes

2021-03-20 22:07 UTC, ulitcos commented on src/stories/fireworks/Fireworks.stories.tsx
> +  title: 'Fireworks mode',
Fireworks example?

2021-03-20 22:07 UTC, ulitcos commented on src/stories/fireworks/Fireworks.tsx
> +    return Object.assign({},
Why are assign here?

2021-03-20 22:07 UTC, ulitcos commented on src/stories/fireworks/Fireworks.tsx
> +          refConfetti={(instance) => this.animationInstance = instance}
Why create every render?

2021-03-20 22:07 UTC, ulitcos commented on src/stories/realisticConfetti/RealisticConfetti.tsx
> +          <button onClick={() => this.fire()}>Fire</button>
Create new every render

2021-03-20 22:07 UTC, ulitcos commented on src/stories/realisticConfetti/RealisticConfetti.tsx
> +    this.animationInstance && this.animationInstance(Object.assign({}, { origin: { y: 0.7 } }, opts, {
Object.assign?

2021-03-23 08:29 UTC, merged